=== ステークホルダマップを作る (design it! / 4章)
[NOTE]
====
plantumlの配置図を使うと良さそう。
使う場合には `direction` の指定がないとシーケンス図になってしまうので注意。
====

[plantuml]
----
@startuml
left to right direction
' top to bottom direction

actor 市民納税者 as 市民
actor 市議会
actor 行政管理予算局_ユーザー as 行管局
actor 市長
actor 地元企業_ユーザー as 地元企業
actor 開発チーム
actor 市の部署_ユーザー as 市部署
actor スプリングフィールド官報新聞 as 新聞
actor 顧問弁護士 as 弁護士

市民 --> 市議会: 投票
市民 --> 市長: 投票
市民 --> 市部署: サービスの依頼

市議会 --> 市長: 方針
市議会 --> 行管局: 方針

行管局 --> 新聞: RFP
行管局 <--> 地元企業: 契約,RFP

市長 --> 開発チーム: 予算から支払い
市長 --> 市部署: 方針
市長 --> 行管局: 方針

地元企業 --> 弁護士: 相談

@enduml
----

ステークホルダーマップを作る際に考えるべきことは次の通り。

* プロジェクトを監督している、またはプロジェクトに資金提供している組織はあるだろうか。
組織内には異なる利権を持つ可能性があるサブグループはあるだろうか。
* プロジェクト最大の貢献社は誰だろうか。
* プロジェクトのソフトウェアはどのようにライセンスされているか。
ライセンスの選択から利益を得ているのはだれか。
* プロジェクトを利用しているのは誰か。
彼らはどのような問題を解決しようとしているか。

=== ステークホルダのビジネス目標を発見する (design it! / 4章)
ステークホルダーのビジネス目標をもとに、品質特性やトレードオフ、技術的負債について検討する。
また、複数の関心事に対して優先順位を設定する。

.一般的なビジネス目標の例
|===
|誰が必要としているか |何を必要としているか

|個人
|富、権力、評判、個人的な楽しみ、知識

|組織
|収益の増加、利益の最大化、事業の拡大、市場のリーダーとなる、安定性の向上、
新しい市場への参入、競合他社から勝利する

|従業員
|興味深く有意義な仕事、知識の向上、ユーザー支援、専門家としての認知

|開発チーム
|特定の品質特性の改善、コストの削減、新機能の追加、標準の実装、
製品化までの時間短縮

|国、政府
|セキュリティ、市民福祉、社会的責任、法令遵守
|===

.具体的なビジネス目標の例
|===
|ステークホルダー |目標 |(目標に対する)コンテキスト

|市長
|調達予算を30%減らす。
|選挙年度に教育やその他の重要なサービスの予算が削減になることを避ける。

|市長
|はじめての地元企業からの申請数や地元企業が獲得した全体的な RFP の割合を測ることで
地元企業と市の関わりを改善する。
|地元企業が市の契約を獲得することで地域経済を向上させる。

|行政管理予算局
|新しい RFP の発行に必要な時間を半分に削減する。
|市内のサービスを改善すると共にコストを削減する。
市のサービスが充実しないと、市民が苦しむことになる。
例）バスケットボールの試合時にトイレットペーパーを用意できない。
救急隊員が使用する注射針が不足する。

|行政管理予算局
|過去10年間の調達データを確認する。
|企業は過去の振る舞いを繰り返すので、過去のデータは契約入札を検討する際に市をサポートする。
|===

ビジネス目標を検討する際に考えるべきことは次の通り。

* ステークホルダーは誰か。彼らは何を得たいと思っているか
* ユーザーは誰か。彼らは何を達成しようとしているか(ソフトウェア以外のことも考慮する)
* 起こりうる最悪の事態は何か。(失敗について考えることでビジネス目標を明らかにできる。人々は失敗を避けたいもの)

=== POV Madlib (design it! / 4章)

穴埋め形式の目標設定ツールで、次のようなテンプレートを穴埋めする。

....
{ステークホルダー} は {ニーズ} をする必要がある。なぜなら、 {コンテキスト} があるからだ。
例）市長は調達コストを30%削減する必要がある。なぜなら、選挙年度に教育予算が削減されるのを避けたいからだ。
....
